openapi: 3.0.3
info:
  version: '2.0'
  title: BridgeLink API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: ''
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Echo
    description: Example echo operations.
  - name: User
    description: Operations about users.
  - name: Tag
    description: This is a tag description.
servers:
  - url: 'http://[localhost]:5001/BridgeLink/2.0'
    description: Local Host
  - url: 'http://[ServerIP]:5001/BridgeLink/2.0'
    description: Hosting Server
paths:
  /Manifest/Query:
    $ref: paths/path-item-with-examples.yaml
    get:
      summary: Query
      operationId: Query
      responses:
        '200':
          $ref: '#/components/responses/Manifest-Query-Response'
      description: Returns all "Manifest" record from the weighbridge manifest.
      parameters: []
    parameters: []
  '/Manifest/Find/{Uid}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/Manifest-Found-Response'
      operationId: get-Manifest-Find
      description: 'Finds & Returns a single "Manifest" record from the weighbridge manifest with the given {Uid} parameter.'
    parameters:
      - $ref: '#/components/parameters/UID'
  '/Manifest/Exist/{Uid}':
    get:
      summary: Exist
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/Manifest-Exist-Response'
        '415':
          description: Unsupported Media Type
      operationId: Exist
      description: 'Returns a Indication on whether or not a "Manifest" entry with the given {Uid} parameter exist.'
      parameters: []
    parameters:
      - $ref: '#/components/parameters/UID'
  /Manifest/Create:
    parameters: []
    post:
      summary: Create
      operationId: post-Manifest-Create
      responses:
        '201':
          $ref: '#/components/responses/Manifest-Query-Response'
      description: Create a single "Manifest" record in the weighbridge manifest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query-Create-Data-Schema'
            examples: {}
        description: ''
  /Manifest/Update:
    put:
      summary: Update
      operationId: put-Manifest-Update
      responses:
        '200':
          $ref: '#/components/responses/Manifest-Updated-Response'
      description: 'Updates a single "Manifest" record in the weighbridge manifest with the given {Uid} parameter'
    parameters: []
  '/Manifest/Delete/{Uid}':
    parameters:
      - $ref: '#/components/parameters/UID'
    delete:
      summary: Delete
      operationId: delete-Manifest-Delete-Uid
      responses:
        '200':
          $ref: '#/components/responses/Manifest-Deleted-Response'
      description: 'Permanently removes a "Manifest" record from the weighbridge manifest with the matching {Uid} parameter'
components:
  securitySchemes: {}
  schemas:
    Manifest-Create-Data-Schema:
      description: ''
      type: object
      x-examples: {}
      title: ''
      properties:
        Client:
          type: object
          properties:
            Urf:
              type: string
              minLength: 0
              maxLength: 50
            Name:
              type: string
              minLength: 0
              maxLength: 50
        Hauler:
          type: object
          properties:
            Name:
              type: string
              minLength: 0
              maxLength: 50
            ContactNumber:
              type: string
              maxLength: 20
              minLength: 0
            PassportNumber:
              type: string
              minLength: 0
              maxLength: 50
            DriversLicenseNumber:
              type: string
              minLength: 0
              maxLength: 50
        Haulier:
          type: object
          properties:
            Urf:
              type: string
              minLength: 0
              maxLength: 50
            Type:
              type: string
              minLength: 0
              maxLength: 50
            Size:
              type: string
              minLength: 0
              maxLength: 50
            VehicleLp:
              type: string
              minLength: 0
              maxLength: 50
            PritrailerLp:
              type: string
              minLength: 0
              maxLength: 50
            SectrailerLp:
              type: string
              minLength: 0
              maxLength: 50
            AxlesLayout:
              type: string
              minLength: 0
              maxLength: 10
        Commodity:
          type: object
          properties:
            Name:
              type: string
              minLength: 0
              maxLength: 20
            Lotnumber:
              type: string
              minLength: 0
              maxLength: 20
            Discription:
              type: string
              minLength: 0
              maxLength: 50
    Query-Create-Data-Schema:
      description: ''
      type: object
      x-examples: {}
      properties:
        status:
          type: string
        query:
          $ref: '#/components/schemas/Manifest-Create-Data-Schema'
        queriedBy:
          type: string
          minLength: 1
      required:
        - status
        - query
        - queriedBy
    Query-Data-Schema:
      description: ''
      type: object
      x-examples: {}
      properties:
        uid:
          type: integer
        tid:
          type: integer
        status:
          type: string
        query:
          $ref: '#/components/schemas/Manifest-Create-Data-Schema'
        queriedBy:
          type: string
          minLength: 1
      required:
        - status
        - query
        - queriedBy
    Manifest-Data-Schema:
      description: ''
      type: object
      x-examples: {}
      properties:
        client:
          type: object
          properties:
            Uid:
              type: integer
              readOnly: true
            Tid:
              type: integer
              readOnly: true
            URF:
              type: string
              minLength: 1
              readOnly: true
            Name:
              type: string
              minLength: 1
          readOnly: true
        hauler:
          type: object
          properties:
            Uid:
              type: integer
            Tid:
              type: integer
            Name:
              type: string
              minLength: 1
            ContactNumber:
              type: string
            PassportNumber:
              type: string
            DriversLicenseNumber:
              type: string
              minLength: 1
        haulier:
          type: object
          properties:
            Uid:
              type: integer
            Tid:
              type: integer
            URF:
              type: string
            Type:
              type: string
              minLength: 1
            Size:
              type: string
              minLength: 1
            VehicleLP:
              type: string
            PRITrailerLP:
              type: string
            SECTrailerLP:
              type: string
            AxlesLayout:
              type: string
              minLength: 1
        commodity:
          type: object
          properties:
            Uid:
              type: integer
            Tid:
              type: integer
            Name:
              type: string
              minLength: 1
            LotNumber:
              type: string
              minLength: 1
            Discription:
              type: string
        transaction:
          type: object
          properties:
            Uid:
              type: integer
            Tid:
              type: integer
            Completed:
              type: boolean
            EntryDate:
              type: string
            EntryTime:
              type: string
            EntryScaleID:
              type: string
            ExitDate:
              type: string
            ExitTime:
              type: string
            ExitScaleID:
              type: string
            Gross:
              type: integer
            Nett:
              type: integer
            Tare:
              type: integer
            ScaleMode:
              type: string
            CreatedBy:
              type: string
  responses:
    Manifest-Deleted-Response:
      description: Responds with the deleted "Manifest" record.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Query-Data-Schema'
          examples: {}
    Manifest-Query-Response:
      description: Returns all "Manifest" records.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Query-Data-Schema'
    Manifest-Found-Response:
      description: 'Returns a "Manifest" record with the matching {Uid} parameter.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Manifest-Data-Schema'
          examples: {}
    Manifest-Exist-Response:
      description: Returns the "Manifest" existance validator.
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                exist: true
            properties:
              exist:
                type: boolean
                default: false
          examples:
            Response Example:
              value:
                exist: false
    Manifest-Updated-Response:
      description: Returns the updated "Manifest" record.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Manifest-Data-Schema'
          examples:
            Response Example:
              value:
                client:
                  Uid: 0
                  Tid: 0
                  URF: string
                  Name: string
                hauler:
                  Uid: 0
                  Tid: 0
                  Name: string
                  ContactNumber: string
                  PassportNumber: string
                  DriversLicenseNumber: string
                haulier:
                  Uid: 0
                  Tid: 0
                  URF: string
                  Type: string
                  Size: string
                  VehicleLP: string
                  PRITrailerLP: string
                  SECTrailerLP: string
                  AxlesLayout: string
                commodity:
                  Uid: 0
                  Tid: 0
                  Name: string
                  LotNumber: string
                  Discription: string
                transaction:
                  Uid: 0
                  Tid: 0
                  Completed: true
                  EntryDate: string
                  EntryTime: string
                  EntryScaleID: string
                  ExitDate: string
                  ExitTime: string
                  ExitScaleID: string
                  Gross: 0
                  Nett: 0
                  Tare: 0
                  ScaleMode: string
                  CreatedBy: string
    Manifest-Created-Response:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Manifest-Data-Schema'
          examples: {}
  parameters:
    UID:
      name: Uid
      in: path
      required: true
      schema:
        type: string
      description: The unique identity of the record
  examples: {}
